cr0 = ["Awakened shrub",
        "Baboon",
        "Badger",
        "Bat",
        "Cat",
        "Commoner",
        "Crab",
        "Crawling claw",
        "Deer",
        "Eagle",
        "Frog",
        "Giant fire beetle",
        "Goat",
        "Hawk",
        "Homunculus",
        "Hyena",
        "Jackal",
        "Lemure",
        "Lizard",
        "Myconid sprout",
        "Octopus",
        "Owl",
        "Quipper",
        "Rat",
        "Raven",
        "Scorpion",
        "Sea horse",
        "Shrieker",
        "Spider",
        "Vulture",
        "Weasel"
       ]
crminder = ["Bandit",
            "Blood hawk",
            "Camel",
            "Cultist",
            "Flumph",
            "Flying snake",
            "Giant crab",
            "Giant rat",
            "Giant weasel",
            "Guard",
            "Kobold",
            "Manes",
            "Mastiff",
            "Merfolk",
            "Monodrone",
            "Mule",
            "Noble",
            "Poisonous snake",
            "Pony",
            "Slaad tadpole"
            ]
crkwart =  ["Aarakocra",
            "Acolyte",
            "Axe beak",
            "Blink dog",
            "Boar",
            "Bullywug",
            "Constrictor snake",
            "Draft horse",
            "Dretch",
            "Drow",
            "Duodrone",
            "Elk",
            "Flying sword",
            "Giant badger",
            "Giant bat",
            "Giant centipede",
            "Giant frog",
            "Giant lizard",
            "Giant owl",
            "Giant poisonous snake",
            "Giant wolf spider",
            "Goblin",
            "Grimlock",
            "Kenku",
            "Kuo-toa",
            "Mud mephit",
            "Needle blight",
            "Panther",
            "Pixie",
            "Pseudodragon",
            "Pteranodon",
            "Riding horse",
            "Skeleton",
            "Smoke mephit",
            "Sprite",
            "Steam mephit",
            "Swarm of bats",
            "Swarm of rats",
            "Swarm of ravens",
            "Troglodyte",
            "Violet fungus",
            "Winged kobold",
            "Wolf",
            "Zombie"
            ]
crhalf = ["Ape",
          "Black Bear",
          "Cockatrice",
          "Crocodile",
          "Darkmantle",
          "Deep Gnome",
          "Dust mephit",
          "Gas spore",
          "Giant goat",
          "Giant sea horse",
          "Giant wasp",
          "Gnoll",
          "Gray ooze",
          "Hobgoblin",
          "Ice mephit",
          "Jackalwere",
          "Lizardfolk",
          "Magma mephit",
          "Magmin",
          "Myconid adult",
          "Orc",
          "Piercer",
          "Reef shark",
          "Rust monster",
          "Sahuagin",
          "Satyr",
          "Scout",
          "Shadow",
          "Swarm of insects",
          "Thug",
          "Tridrone",
          "Vine blight",
          "Warhorse",
          "Warhorse skeleton",
          "Worg",
          ]
cr1 = ["Animated armor",
       "Brass dragon wyrmling",
       "Brown bear",
       "Bugbear",
       "Copper dragon wyrmling",
       "Death dog",
       "Dire wolf",
       "Dryad",
       "Duergar",
       "Faerie dragon (young)",
       "Fire snake",
       "Ghoul",
       "Giant eagle",
       "Giant hyena",
       "Giant octopus",
       "Giant spider",
       "Giant toad",
       "Giant vulture",
       "Goblin boss",
       "Half ogre",
       "Harpy",
       "Hippogriff",
       "Imp",
       "Kuo-toa-whip",
       "Lion",
       "Quadrone",
       "Quaggoth spore servant",
       "Quasit",
       "Scarecrow",
       "Specter",
       "Spy",
       "Swarm of quippers",
       "Thri-kreen",
       "Tiger",
       "Yuan-ti pureblood"
       ]
cr2 = ["Allosaurus",
        "Ankheg",
        "Awakened tree",
        "Azer",
        "Bandit captain",
        "Berserker",
        "Black dragon wyrmling",
        "Bronze dragon wyrmling",
        "Carrion crawler",
        "Centaur",
        "Cult fanatic",
        "Druid",
        "Ettercap",
        "Faerie dragon (old)",
        "Gargoyle",
        "Gelatinous cube",
        "Ghast",
        "Giant boar",
        "Giant constrictor snake",
        "Giant elk",
        "Gibbering mouther",
        "Githzerai monk",
        "Gnoll pack lord",
        "Green dragon wyrmling",
        "Grick",
        "Griffon",
        "Hunter shark",
        "Intellect devourer",
        "Lizardfolk shaman",
        "Merrow",
        "Mimic",
        "Minotaur skeleton",
        "Myconid sovereign",
        "Nothic",
        "Ochre jelly",
        "Ogre",
        "Ogre zombie",
        "Orc Eye of Gruumsh",
        "Orog",
        "Pegasus",
        "Pentadrone",
        "Peryton",
        "Plesiosaurus",
        "Polar bear",
        "Poltergeist (specter)",
        "Priest",
        "Quaggoth",
        "Rhinoceros",
        "Rug of smothering",
        "Saber-toothed tiger",
        "Sahuagin priestess",
        "Sea hag",
        "Silver dragon wyrmling",
        "Spined devil",
        "Swarm of poisonous snakes",
        "Wererat",
        "White dragon wyrmling",
        "Will-o’-wisp"
       ]
cr3 = ["Ankylosaurus",
        "Basilisk",
        "Bearded devil",
        "Blue dragon wyrmling",
        "Bugbear chief",
        "Displacer beast",
        "Doppelganger",
        "Giant scorpion",
        "Githyanki warrior",
        "Gold dragon wyrmling",
        "Green hag",
        "Grell",
        "Hell hound",
        "Hobgoblin captain",
        "Hook horror",
        "Killer whale",
        "Knight",
        "Kuo-toa monitor",
        "Manticore",
        "Minotaur",
        "Mummy",
        "Nightmare",
        "Owlbear",
        "Phase spider",
        "Quaggoth thonot",
        "Spectator",
        "Veteran",
        "Water weird",
        "Werewolf",
        "Wight",
        "Winter wolf",
        "Yeti",
        "Yuan-ti malison"
       ]
cr4 = ["Banshee",
        "Black pudding",
        "Bone naga",
        "Chuul",
        "Couatl",
        "Elephant",
        "Ettin",
        "Flameskull",
        "Ghost",
        "Gnoll fang of Yeenoghu",
        "Helmed horror",
        "Incubus"
        "Lamia"
        "Lizard king/queen",
        "Orc war chief",
        "Red dragon wyrmling",
        "Sea hag (in coven)",
        "Shadow demon",
        "Succubus",
        "Wereboar",
        "Weretiger"
       ]
cr5 = ["Air elemental",
        "Barbed devil",
        "Barlgura",
        "Beholder zombie",
        "Bulette",
        "Cambion"
        "Drow elite warrior",
        "Earth elemental",
        "Fire elemental",
        "Flesh golem",
        "Giant crocodile",
        "Giant shark",
        "Gladiator",
        "Gorgon",
        "Green hag (in coven)",
        "Half-red dragon veteran",
        "Hill giant",
        "Mezzoloth",
        "Night hag",
        "Otyugh",
        "Red slaad",
        "Revenant",
        "Roper",
        "Sahuagin baron",
        "Salamander",
        "Shambling mound",
        "Triceratops",
        "Troll",
        "Umber hulk",
        "Unicorn",
        "Vampire spawn",
        "Water elemental",
        "Werebear",
        "Wraith",
        "Xorn",
        "Young remorhaz"
       ]
cr6 = ["Chasme",
        "Chimera",
        "Cyclops",
        "Drider",
        "Galeb duhr",
        "Githzerai zerth",
        "Hobgoblin warlord",
        "Invisible stalker",
        "Kuo-toa archpriest",
        "Mage",
        "Mammoth",
        "Medusa",
        "Vrock",
        "Wyvern",
        "Young brass dragon",
        "Young white dragon"
    ]
cr7 = ["Blue slaad",
        "Drow mage",
        "Giant ape",
        "Grick alpha",
        "Mind flayer",
        "Night hag (in coven)",
        "Oni",
        "Shield guardian",
        "Stone giant",
        "Young black dragon",
        "Young copper dragon"
        "Yuan-ti abomination"
       ]
cr8 = ["Assassin",
        "Chain devil",
        "Cloaker",
        "Drow priestess of Lolth",
        "Fomorian",
        "Frost giant",
        "Githyanki knight",
        "Green slaad",
        "Hezrou",
        "Hydra",
        "Mind flayer arcanist",
        "Spirit naga",
        "Tyrannosaurus rex",
        "Young bronze dragon",
        "Young green dragon"
       ]
cr9 = ["Abominable yeti",
        "Bone devil",
        "Clay golem",
        "Cloud giant",
        "Fire giant",
        "Glabrezu",
        "Gray slaad",
        "Nycaloth",
        "Treant",
        "Young blue dragon",
        "Young silver dragon"
       ]
cr10 = ["Aboleth",
        "Death slaad",
        "Deva",
        "Guardian naga",
        "Stone golem",
        "Yochlol",
        "Young gold dragon",
        "Young red dragon"
        ]
cr11 = ["Behir",
        "Dao",
        "Djinni",
        "Efreeti",
        "Gynosphinx",
        "Horned devil",
        "Marid",
        "Remorha",
        "Roc"
        ]
cr12 = ["Arcanaloth",
        "Archmage",
        "Erinyes"
        ]
cr13 = ["Adult brass dragon",
        "Adult white dragon",
        "Beholder (not in lair)",
        "Nalfeshnee",
        "Rakshasa",
        "Storm giant",
        "Ultroloth",
        "Vampire",
        "Young red shadow dragon"
        ]
cr14 = ["Adult black dragon",
        "Adult copper dragon",
        "Beholder (in lair)",
        "Death tyrant (not in lair)",
        "Ice devil"
        ]
cr15 = ["Adult bronze dragon",
        "Adult green dragon",
        "Death tyrant (in lair)",
        "Mummy lord (not in lair)",
        "Purple worm",
        "Vampire (spellcaster)",
        "Vampire (warrior)"
        ]
cr16 = ["Adult blue dragon",
        "Adult silver dragon",
        "Iron golem",
        "Marilith",
        "Mummy lord (in lair)",
        "Planetar"
        ]
cr17 = ["Adult blue dracolich",
        "Adult gold dragon",
        "Adult red dragon",
        "Androsphinx",
        "Death knight",
        "Dragon turtle",
        "Goristro"
        ]
cr18 = ["Demilich (not in lair)"]
cr19 = ["Balor"]
cr20 = ["Ancient brass dragon",
        "Ancient white dragon",
        "Demilich (in lair)",
        "Pit fiend"
        ]
cr21 = ["Ancient black dragon",
        "Ancient copper dragon",
        "Lich (not in lair)",
        "Solar"
        ]
cr22 = ["Ancient bronze dragon",
        "Ancient green dragon",
        "Lich (in lair)"
        ]
cr23 = ["Ancient blue dragon",
        "Ancient silver dragon",
        "Empyrean",
        "Kraken"
        ]
cr24 = ["Ancient gold dragon",
        "Ancient red dragon"
        ]
cr30 = ["Tarrasque"]
