crhalf = ["Ape",
          "Black Bear",
          "Cockatrice",
          "Crocodile",
          "Darkmantle",
          "Deep Gnome",
          "Dust mephit",
          "Gas spore",
          "Giant goat",
          "Giant sea horse",
          "Giant wasp",
          "Gnoll",
          "Gray ooze",
          "Hobgoblin",
          "Ice mephit",
          "Jackalwere",
          "Lizardfolk",
          "Magma mephit",
          "Magmin",
          "Myconid adult",
          "Orc",
          "Piercer",
          "Reef shark",
          "Rust monster",
          "Sahuagin",
          "Satyr",
          "Scout",
          "Shadow",
          "Swarm of insects",
          "Thug",
          "Tridrone",
          "Vine blight",
          "Warhorse",
          "Warhorse skeleton",
          "Worg",
          ]
cr1 = ["Animated armor",
       "Brass dragon wyrmling",
       "Brown bear",
       "Bugbear",
       "Copper dragon wyrmling",
       "Death dog",
       "Dire wolf",
       "Dryad",
       "Duergar",
       "Faerie dragon (young)",
       "Fire snake",
       "Ghoul",
       "Giant eagle",
       "Giant hyena",
       "Giant octopus",
       "Giant spider",
       "Giant toad",
       "Giant vulture",
       "Goblin boss",
       "Half ogre",
       "Harpy",
       "Hippogriff",
       "Imp",
       "Kuo-toa-whip",
       "Lion",
       "Quadrone",
       "Quaggoth spore servant",
       "Quasit",
       "Scarecrow",
       "Specter",
       "Spy",
       "Swarm of quippers",
       "Thri-kreen",
       "Tiger",
       "Yuan-ti pureblood"
       ]
cr2 = ["Allosaurus",
        "Ankheg",
        "Awakened tree",
        "Azer",
        "Bandit captain",
        "Berserker",
        "Black dragon wyrmling",
        "Bronze dragon wyrmling",
        "Carrion crawler",
        "Centaur",
        "Cult fanatic",
        "Druid",
        "Ettercap",
        "Faerie dragon (old)",
        "Gargoyle",
        "Gelatinous cube",
        "Ghast",
        "Giant boar",
        "Giant constrictor snake",
        "Giant elk",
        "Gibbering mouther",
        "Githzerai monk",
        "Gnoll pack lord",
        "Green dragon wyrmling",
        "Grick",
        "Griffon",
        "Hunter shark",
        "Intellect devourer",
        "Lizardfolk shaman",
        "Merrow",
        "Mimic",
        "Minotaur skeleton",
        "Myconid sovereign",
        "Nothic",
        "Ochre jelly",
        "Ogre",
        "Ogre zombie",
        "Orc Eye of Gruumsh",
        "Orog",
        "Pegasus",
        "Pentadrone",
        "Peryton",
        "Plesiosaurus",
        "Polar bear",
        "Poltergeist (specter)",
        "Priest",
        "Quaggoth",
        "Rhinoceros",
        "Rug of smothering",
        "Saber-toothed tiger",
        "Sahuagin priestess",
        "Sea hag",
        "Silver dragon wyrmling",
        "Spined devil",
        "Swarm of poisonous snakes",
        "Wererat",
        "White dragon wyrmling",
        "Will-o’-wisp"
       ]
cr3 = ["Ankylosaurus",
        "Basilisk",
        "Bearded devil",
        "Blue dragon wyrmling",
        "Bugbear chief",
        "Displacer beast",
        "Doppelganger",
        "Giant scorpion",
        "Githyanki warrior",
        "Gold dragon wyrmling",
        "Green hag",
        "Grell",
        "Hell hound",
        "Hobgoblin captain",
        "Hook horror",
        "Killer whale",
        "Knight",
        "Kuo-toa monitor",
        "Manticore",
        "Minotaur",
        "Mummy",
        "Nightmare",
        "Owlbear",
        "Phase spider",
        "Quaggoth thonot",
        "Spectator",
        "Veteran",
        "Water weird",
        "Werewolf",
        "Wight",
        "Winter wolf",
        "Yeti",
        "Yuan-ti malison"
       ]
