crhalf = ["Ape",
          "Black Bear",
          "Cockatrice",
          "Crocodile",
          "Darkmantle",
          "Deep Gnome",
          "Dust mephit",
          "Gas spore",
          "Giant goat",
          "Giant sea horse",
          "Giant wasp",
          "Gnoll",
          ]
