"""This file sorts out all of the existing briefs, descriptions and aliases for current and future commands all in the proper order.
Make sure you add new aliases, descriptions or briefs in the correct place when adding to this file."""

# about
aboutbrief = "Always been curious who made this bot? Find out by running this command."
aboutalias = ['info']
aboutdescription = "Gives an overview of who made the bot, who contributed it and when it got released. In this command current developers are shown as well as previous ones."
# advantage
advantagebrief = "Rolls dices with advantage."
advantagealias = ['adv']
advantagedescription = "Rolls dices with advantage. Format like: ;advantage {dicetype}. Multiple dicetypes can be rolled."
# basic
basicbrief = "Quick reference to the 5e d&d rulebook."
basicealias = ['basicrules', 'basicrule']
basicdescription = "Quick reference to the 5e d&d rulebook."
# character
characterbrief = "Generate a level 1 character."
characteralias = ['char', 'randchar']
characterdescription = "Generates a level 1 character, with detailed stats, equipment, traits, appearance and much more."
# class
classbrief = "Get the details of any d&d 5e class."
classalias = ['classes']
classdescription = "Get the basic information of any d&d 5e official class, homebrew not included. This does not get the information of feats, but only when you obtain them."
# condition
conditionbrief = "Get the information about conditions in d&d 5e."
conditionalias = ['con']
conditiondescription = "Get the information about conditions in d&d 5e. The ones with tables have been changed as it can't be shown on discord."
# currency
currencybrief = "Calculates your lower value currency, into the highest possible value."
currencyalias = ['cur']
currencydescription = "Calculates your lower value currency, into the highest possible value. Format like: ;currency {currency}, for example: ;currency 40sp 50gp."
# disadvantage
disadvantagebrief = "Rolls dices with disadvantage"
disadvantagealias = ['disadv']
disadvantagdescription = "Rolls dices with disadvantage. Format like: ;disadvantage {dicetype}. Multiple dicetypes can be rolled."
# encounter
encounterbrief = "Generates an encounter for a party level up to a size of 8 and a level of 20."
encounteralias = ['enc', 'encgen']
encounterdescription = "Generates an encounter for a party level up to a size of 8 and a level of 20. Format like: ;encounter {pclevel} {pcamount}."
# help
helpbrief = "Shows this list"
helpalias = ['h']
helpdescription = "List of all non-guild only commands"
# invite
invitebrief = "Sends you an up to date link to invite the bot to your server."
invitealias = ['inv']
invitedescription = "Sends you an up to date link to invite the bot to your server."
# npc
npcbrief = "Generate an npc."
npcalias = ['npcgen', 'rannpc']
npcdescription = "Generates an npc that includes, appearance, traits, stats and much more."
# rngstat
rngstatbrief = "Roll up to 25 ability scores."
rngstatalias = ['rng', 'rngstats']
rngstatdescription = "Roll up to 25 ability scores. Ability scores are generated by rolling a 6 sided die 4 times and then adding the highest 3 up. Format like: ;rngstat {amount}."
# roll
rollbrief = "Roll a numerous amount of dices."
rollalias = ['r', 'roller']
rolldescription = "Roll a numerous amount of dices. Format like: ;roll {dicetype}. For example: ;roll 4d10 3d6. Multiple dices can be given."
# rprule
rprulebrief = "Rules for the tavern rp section."
rprulealias = ['rprules', 'rp']
rpruledescription = "Rules for the tavern rp section. This is a Tavern only command."
# rule
rulebrief = "Rules for the tavern."
rulealias = ['rule', 'tavernrule']
ruledescription = "Rules for the tavern. They are listed in #welcome-rules. This is a Tavern only command."
# spell
spellbrief = "Get the details of any 5e spell."
spellalias = []
spelldescription = "Get the basic information of any d&d 5e official spell, homebrew not included. Spells with tables with them can unfortunately not be completely shown."
# status
statusbrief = "The bots current wherabouts."
statusalias = ['botstatus']
statusdescription = "The bots current whereabouts. Displays the amount of servers and its members respectively. This is mostly for testing if the bot is online."
# super-advantage
superadvantagebrief = "Rolls dices with super-advantage."
superadvantagealias = ['superadv']
superadvantagedescription = "Rolls dices with super-advantage. Format like: ;super-advantage {dicetype}. Multiple dicetypes can be rolled."
# super-disadvantage
superdisadvantagebrief = "Rolls dices with super-disadvantage."
superdisadvantagealias = ['superdisadv']
superdisadvantagedescription = "Rolls dices with super-disadvantage. Format like: ;super-disadvantage {dicetype}. Multiple dicetypes can be rolled."
# tavernhelp
tavernhelpbrief = "Shows all the Tavern only commands."
tavernhelpalias = ['thelp']
tavernhelpdescription = "Shows all the Tavern only commands."
